name: desafio-um

on:
  push:
    branches:
      - desafio-um

jobs:
  download-image-docker:
  runs-on: ubuntu-latest
  steps:
    - name: Download Image Docker
      run: docker pull hello-world
    
    - name: Image List
      run: docker images