name: Primeiro Workflow Curso GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release
      
      - name: Exibir uma mensagem
        run: echo "Meu primeiro workflow do curso de GitHub Actions"